# This is default jargon that you can use. Feel free to change it. See: https://boogi.netlify.app/editing/rich_content/abbreviations
'manifold':
  name: manifold
  long_name: manifoldfinance
  description: Manifold Finance Documentation and Wiki
